#!/usr/bin/env bash

set -euo pipefail

name="app"
lang="cpp"

read -p "Enter project name: " name

if [[ ! "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
	printf "Invalid project name\n"
	exit 1
fi

declare -A choices=(
	["C"]='c'
	["C++"]='cpp'
)
label=$(printf "%s\n" "${!choices[@]}" | fzf --prompt="Choose your language")
lang="${choices[$label]}"

case "$lang" in
c)
	std="c_std=c23"
	;;
cpp)
	std="cpp_std=c++23"
	;;
esac

cat <<EOF >meson.build
project('$name', '$lang',
  version: '1.0',
  default_options: [
    '$std',
    'warning_level=3',
    'werror=true'
  ]
)

inc = include_directories('include')

src = files(
  'src/main.$lang'
)
executable('$name',
  sources: src,
  include_directories: inc,
  install: true
)
EOF

cat <<EOF >justfile
run: build
	./build/$name

build:
	meson compile -C build

setup buildtype="debug" compiler="clang":
	if [ "{{compiler}}" = "gcc" ]; then \\
		CC=gcc CXX=g++ meson setup build --buildtype={{buildtype}}; \\
	else \\
		CC=clang CXX=clang++ meson setup build --buildtype={{buildtype}}; \\
	fi 
EOF

mkdir ./src ./include
touch ./src/main."$lang"
