#!/usr/bin/env bash

set -euo pipefail

name="app"
lang="cpp"

if ! command -v whiptail; then
	prinf "Whiptail is not installed.\n"
	exit 1
fi

if ! name=$(
	whiptail \
		--inputbox "Enter project name:" 10 50 "$name" \
		3>&1 1>&2 2>&3
); then
	printf "User Cancelled\n"
	exit 1
fi

if [[ ! "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
	printf "Invalid project name\n"
	exit 1
fi

if ! lang=$(
	whiptail \
		--menu "Choose your language" 15 50 2 \
		c "C" \
		cpp "C++" \
		3>&1 1>&2 2>&3
); then
	printf "User Cancelled\n"
	exit 1
fi

clear

case "$lang" in
c)
	std="c_std=c23"
	;;
cpp)
	std="cpp_std=c++23"
	;;
esac

cat <<EOF >meson.build
project('$name', '$lang',
  version: '1.0',
  default_options: [
    '$std',
    'warning_level=3',
    'werror=true'
  ]
)

inc = include_directories('include')

src = files(
  'src/main.$lang'
)
executable('$name',
  sources: src,
  include_directories: inc,
  install: true
)
EOF

cat <<EOF >justfile
run: build
	./build/$name

build:
	meson compile -C build

setup buildtype="debug" compiler="clang":
	if [ "{{compiler}}" = "gcc" ]; then \\
		CC=gcc CXX=g++ meson setup build --buildtype={{buildtype}}; \\
	else \\
		CC=clang CXX=clang++ meson setup build --buildtype={{buildtype}}; \\
	fi 
EOF

mkdir ./src ./include
touch ./src/main."$lang"
